### ISSUE TITLE
.pkgen.ymlのフィールド名で.記法でディレクトリを一括作成できるようにする

### ISSUE THREAD

**Issue by inadati** [overgrow888/pkgen#1]
## 現状
下記のような.pkgen.ymlを基に`pkgen`を実行すると  
`print.clerk.services`という名前のディレクトリがそのまま生成されてしまう。
```yaml
pkg:
  store:
    print.clerk.services:
```

## 改善詳細
print.clerk.servicesというフィールド名は再帰的にディレクトリを生成するようにする。
